# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import memsource_cli
from memsource_cli.api.job_api import JobApi  # noqa: E501
from memsource_cli.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = memsource_cli.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compare_part(self):
        """Test case for compare_part

        Compare jobs on workflow levels  # noqa: E501
        """
        pass

    def test_completed_file(self):
        """Test case for completed_file

        Download target file  # noqa: E501
        """
        pass

    def test_create_job(self):
        """Test case for create_job

        Create job  # noqa: E501
        """
        pass

    def test_create_term_by_job(self):
        """Test case for create_term_by_job

        Create term in job's term bases  # noqa: E501
        """
        pass

    def test_delete_all_translations(self):
        """Test case for delete_all_translations

        Delete all translations  # noqa: E501
        """
        pass

    def test_delete_parts(self):
        """Test case for delete_parts

        Delete job (batch)  # noqa: E501
        """
        pass

    def test_edit_part(self):
        """Test case for edit_part

        Edit job  # noqa: E501
        """
        pass

    def test_edit_parts(self):
        """Test case for edit_parts

        Edit jobs (batch)  # noqa: E501
        """
        pass

    def test_file_preview(self):
        """Test case for file_preview

        Download preview file  # noqa: E501
        """
        pass

    def test_file_preview_job(self):
        """Test case for file_preview_job

        Download preview file  # noqa: E501
        """
        pass

    def test_get_bilingual_file(self):
        """Test case for get_bilingual_file

        Download bilingual file  # noqa: E501
        """
        pass

    def test_get_completed_file_warnings(self):
        """Test case for get_completed_file_warnings

        Get target file's warnings  # noqa: E501
        """
        pass

    def test_get_original_file(self):
        """Test case for get_original_file

        Download original file  # noqa: E501
        """
        pass

    def test_get_part(self):
        """Test case for get_part

        Get job  # noqa: E501
        """
        pass

    def test_get_parts_workflow_step(self):
        """Test case for get_parts_workflow_step

        Get job's workflowStep  # noqa: E501
        """
        pass

    def test_get_segments_count(self):
        """Test case for get_segments_count

        Get segments count  # noqa: E501
        """
        pass

    def test_get_translation_resources(self):
        """Test case for get_translation_resources

        Get translation resources  # noqa: E501
        """
        pass

    def test_list_part_analyse1(self):
        """Test case for list_part_analyse1

        List analyses  # noqa: E501
        """
        pass

    def test_list_parts_v2(self):
        """Test case for list_parts_v2

        List jobs  # noqa: E501
        """
        pass

    def test_list_providers1(self):
        """Test case for list_providers1

        Get suggested providers  # noqa: E501
        """
        pass

    def test_list_segments(self):
        """Test case for list_segments

        Get segments  # noqa: E501
        """
        pass

    def test_notify_assigned(self):
        """Test case for notify_assigned

        Notify assigned users  # noqa: E501
        """
        pass

    def test_preview_urls(self):
        """Test case for preview_urls

        Get PDF preview  # noqa: E501
        """
        pass

    def test_pseudo_translate(self):
        """Test case for pseudo_translate

        Pseudo-translate job  # noqa: E501
        """
        pass

    def test_pseudo_translate_job_part(self):
        """Test case for pseudo_translate_job_part

        Pseudo-translates job  # noqa: E501
        """
        pass

    def test_search_by_job3(self):
        """Test case for search_by_job3

        Search job's translation memories  # noqa: E501
        """
        pass

    def test_search_parts_in_project(self):
        """Test case for search_parts_in_project

        Search jobs in project  # noqa: E501
        """
        pass

    def test_search_segment_by_job(self):
        """Test case for search_segment_by_job

        Search translation memory for segment by job  # noqa: E501
        """
        pass

    def test_search_terms_by_job1(self):
        """Test case for search_terms_by_job1

        Search job's term bases  # noqa: E501
        """
        pass

    def test_search_terms_in_text_by_job_v2(self):
        """Test case for search_terms_in_text_by_job_v2

        Search terms in text  # noqa: E501
        """
        pass

    def test_set_status(self):
        """Test case for set_status

        Edit job status  # noqa: E501
        """
        pass

    def test_split(self):
        """Test case for split

        Split job  # noqa: E501
        """
        pass

    def test_status_changes(self):
        """Test case for status_changes

        Get status changes  # noqa: E501
        """
        pass

    def test_upload_bilingual_file(self):
        """Test case for upload_bilingual_file

        Upload bilingual file  # noqa: E501
        """
        pass

    def test_web_editor_link_v2(self):
        """Test case for web_editor_link_v2

        Get Web Editor URL  # noqa: E501
        """
        pass

    def test_wild_card_search_by_job3(self):
        """Test case for wild_card_search_by_job3

        Wildcard search job's translation memories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
