# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import memsource_cli
from memsource_cli.models.name_dto import NameDto  # noqa: E501
from memsource_cli.rest import ApiException


class TestNameDto(unittest.TestCase):
    """NameDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNameDto(self):
        """Test NameDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = memsource_cli.models.name_dto.NameDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
