# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import memsource_cli
from memsource_cli.api.project_template_api import ProjectTemplateApi  # noqa: E501
from memsource_cli.rest import ApiException


class TestProjectTemplateApi(unittest.TestCase):
    """ProjectTemplateApi unit test stubs"""

    def setUp(self):
        self.api = memsource_cli.api.project_template_api.ProjectTemplateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_linguists_from_template(self):
        """Test case for assign_linguists_from_template

        Assigns providers from template  # noqa: E501
        """
        pass

    def test_assign_linguists_from_template_to_job_parts(self):
        """Test case for assign_linguists_from_template_to_job_parts

        Assigns providers from template (specific jobs)  # noqa: E501
        """
        pass

    def test_assignable_templates(self):
        """Test case for assignable_templates

        List assignable templates  # noqa: E501
        """
        pass

    def test_create_project_from_template_v2(self):
        """Test case for create_project_from_template_v2

        Create project from template  # noqa: E501
        """
        pass

    def test_create_project_template(self):
        """Test case for create_project_template

        Create project template  # noqa: E501
        """
        pass

    def test_delete_project_template(self):
        """Test case for delete_project_template

        Delete project template  # noqa: E501
        """
        pass

    def test_edit_project_template(self):
        """Test case for edit_project_template

        Edit project template  # noqa: E501
        """
        pass

    def test_get_analyse_settings_for_project_template(self):
        """Test case for get_analyse_settings_for_project_template

        Get analyse settings  # noqa: E501
        """
        pass

    def test_get_machine_translate_settings_for_project_template(self):
        """Test case for get_machine_translate_settings_for_project_template

        Get machine translate settings  # noqa: E501
        """
        pass

    def test_get_pre_translate_settings_for_project_template(self):
        """Test case for get_pre_translate_settings_for_project_template

        Get Pre-translate settings  # noqa: E501
        """
        pass

    def test_get_project_template(self):
        """Test case for get_project_template

        Get project template  # noqa: E501
        """
        pass

    def test_get_project_template_term_bases(self):
        """Test case for get_project_template_term_bases

        Get term bases  # noqa: E501
        """
        pass

    def test_get_project_template_trans_memories(self):
        """Test case for get_project_template_trans_memories

        Get translation memories  # noqa: E501
        """
        pass

    def test_get_project_templates(self):
        """Test case for get_project_templates

        List project templates  # noqa: E501
        """
        pass

    def test_set_project_template_term_bases(self):
        """Test case for set_project_template_term_bases

        Edit term bases in project template  # noqa: E501
        """
        pass

    def test_set_project_template_trans_memories(self):
        """Test case for set_project_template_trans_memories

        Edit translation memories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
