# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import memsource_cli
from memsource_cli.api.conversations_api import ConversationsApi  # noqa: E501
from memsource_cli.rest import ApiException


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self):
        self.api = memsource_cli.api.conversations_api.ConversationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_lqa_comment(self):
        """Test case for add_lqa_comment

        Add LQA comment  # noqa: E501
        """
        pass

    def test_add_plain_comment(self):
        """Test case for add_plain_comment

        Add plain comment  # noqa: E501
        """
        pass

    def test_create_lqa_conversation(self):
        """Test case for create_lqa_conversation

        Create LQA conversation  # noqa: E501
        """
        pass

    def test_create_segment_target_conversation(self):
        """Test case for create_segment_target_conversation

        Create plain conversation  # noqa: E501
        """
        pass

    def test_delete_lqa_comment(self):
        """Test case for delete_lqa_comment

        Delete LQA comment  # noqa: E501
        """
        pass

    def test_delete_lqa_conversation(self):
        """Test case for delete_lqa_conversation

        Delete conversation  # noqa: E501
        """
        pass

    def test_delete_plain_comment(self):
        """Test case for delete_plain_comment

        Delete plain comment  # noqa: E501
        """
        pass

    def test_delete_plain_conversation(self):
        """Test case for delete_plain_conversation

        Delete plain conversation  # noqa: E501
        """
        pass

    def test_find_conversations(self):
        """Test case for find_conversations

        Find all conversation  # noqa: E501
        """
        pass

    def test_get_lqa_conversation(self):
        """Test case for get_lqa_conversation

        Get LQA conversation  # noqa: E501
        """
        pass

    def test_get_plain_conversation(self):
        """Test case for get_plain_conversation

        Get plain conversation  # noqa: E501
        """
        pass

    def test_list_all_conversations(self):
        """Test case for list_all_conversations

        List all conversations  # noqa: E501
        """
        pass

    def test_list_lqa_conversations(self):
        """Test case for list_lqa_conversations

        List LQA conversations  # noqa: E501
        """
        pass

    def test_list_plain_conversations(self):
        """Test case for list_plain_conversations

        List plain conversations  # noqa: E501
        """
        pass

    def test_update_lqa_comment(self):
        """Test case for update_lqa_comment

        Edit LQA comment  # noqa: E501
        """
        pass

    def test_update_lqa_conversation(self):
        """Test case for update_lqa_conversation

        Edit LQA conversation  # noqa: E501
        """
        pass

    def test_update_plain_comment(self):
        """Test case for update_plain_comment

        Edit plain comment  # noqa: E501
        """
        pass

    def test_update_plain_conversation(self):
        """Test case for update_plain_conversation

        Edit plain conversation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
