# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from memsource_cli.models.lqa_reference import LQAReference  # noqa: F401,E501


class EditLQAConversationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lqa': 'list[LQAReference]',
        'status': 'str'
    }

    attribute_map = {
        'lqa': 'lqa',
        'status': 'status'
    }

    def __init__(self, lqa=None, status=None):  # noqa: E501
        """EditLQAConversationDto - a model defined in Swagger"""  # noqa: E501

        self._lqa = None
        self._status = None
        self.discriminator = None

        self.lqa = lqa
        if status is not None:
            self.status = status

    @property
    def lqa(self):
        """Gets the lqa of this EditLQAConversationDto.  # noqa: E501


        :return: The lqa of this EditLQAConversationDto.  # noqa: E501
        :rtype: list[LQAReference]
        """
        return self._lqa

    @lqa.setter
    def lqa(self, lqa):
        """Sets the lqa of this EditLQAConversationDto.


        :param lqa: The lqa of this EditLQAConversationDto.  # noqa: E501
        :type: list[LQAReference]
        """
        if lqa is None:
            raise ValueError("Invalid value for `lqa`, must not be `None`")  # noqa: E501

        self._lqa = lqa

    @property
    def status(self):
        """Gets the status of this EditLQAConversationDto.  # noqa: E501


        :return: The status of this EditLQAConversationDto.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this EditLQAConversationDto.


        :param status: The status of this EditLQAConversationDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["resolved", "unresolved"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditLQAConversationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditLQAConversationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
