# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobStatusChangeActionDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'requested_status': 'str',
        'notify_owner': 'bool'
    }

    attribute_map = {
        'requested_status': 'requestedStatus',
        'notify_owner': 'notifyOwner'
    }

    def __init__(self, requested_status=None, notify_owner=None):  # noqa: E501
        """JobStatusChangeActionDto - a model defined in Swagger"""  # noqa: E501

        self._requested_status = None
        self._notify_owner = None
        self.discriminator = None

        if requested_status is not None:
            self.requested_status = requested_status
        if notify_owner is not None:
            self.notify_owner = notify_owner

    @property
    def requested_status(self):
        """Gets the requested_status of this JobStatusChangeActionDto.  # noqa: E501


        :return: The requested_status of this JobStatusChangeActionDto.  # noqa: E501
        :rtype: str
        """
        return self._requested_status

    @requested_status.setter
    def requested_status(self, requested_status):
        """Sets the requested_status of this JobStatusChangeActionDto.


        :param requested_status: The requested_status of this JobStatusChangeActionDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["NEW", "ACCEPTED", "DECLINED", "REJECTED", "DELIVERED", "EMAILED", "COMPLETED", "CANCELLED"]  # noqa: E501
        if requested_status not in allowed_values:
            raise ValueError(
                "Invalid value for `requested_status` ({0}), must be one of {1}"  # noqa: E501
                .format(requested_status, allowed_values)
            )

        self._requested_status = requested_status

    @property
    def notify_owner(self):
        """Gets the notify_owner of this JobStatusChangeActionDto.  # noqa: E501

        Default: false  # noqa: E501

        :return: The notify_owner of this JobStatusChangeActionDto.  # noqa: E501
        :rtype: bool
        """
        return self._notify_owner

    @notify_owner.setter
    def notify_owner(self, notify_owner):
        """Sets the notify_owner of this JobStatusChangeActionDto.

        Default: false  # noqa: E501

        :param notify_owner: The notify_owner of this JobStatusChangeActionDto.  # noqa: E501
        :type: bool
        """

        self._notify_owner = notify_owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobStatusChangeActionDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobStatusChangeActionDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
