# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from memsource_cli.models.user_reference import UserReference  # noqa: F401,E501


class LoginToSessionResponseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'UserReference',
        'cookie': 'str',
        'csrf_token': 'str'
    }

    attribute_map = {
        'user': 'user',
        'cookie': 'cookie',
        'csrf_token': 'csrfToken'
    }

    def __init__(self, user=None, cookie=None, csrf_token=None):  # noqa: E501
        """LoginToSessionResponseDto - a model defined in Swagger"""  # noqa: E501

        self._user = None
        self._cookie = None
        self._csrf_token = None
        self.discriminator = None

        if user is not None:
            self.user = user
        if cookie is not None:
            self.cookie = cookie
        if csrf_token is not None:
            self.csrf_token = csrf_token

    @property
    def user(self):
        """Gets the user of this LoginToSessionResponseDto.  # noqa: E501


        :return: The user of this LoginToSessionResponseDto.  # noqa: E501
        :rtype: UserReference
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this LoginToSessionResponseDto.


        :param user: The user of this LoginToSessionResponseDto.  # noqa: E501
        :type: UserReference
        """

        self._user = user

    @property
    def cookie(self):
        """Gets the cookie of this LoginToSessionResponseDto.  # noqa: E501


        :return: The cookie of this LoginToSessionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._cookie

    @cookie.setter
    def cookie(self, cookie):
        """Sets the cookie of this LoginToSessionResponseDto.


        :param cookie: The cookie of this LoginToSessionResponseDto.  # noqa: E501
        :type: str
        """

        self._cookie = cookie

    @property
    def csrf_token(self):
        """Gets the csrf_token of this LoginToSessionResponseDto.  # noqa: E501


        :return: The csrf_token of this LoginToSessionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._csrf_token

    @csrf_token.setter
    def csrf_token(self, csrf_token):
        """Sets the csrf_token of this LoginToSessionResponseDto.


        :param csrf_token: The csrf_token of this LoginToSessionResponseDto.  # noqa: E501
        :type: str
        """

        self._csrf_token = csrf_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoginToSessionResponseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginToSessionResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
