# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SpellCheckRequestDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lang': 'str',
        'texts': 'list[str]',
        'reference_texts': 'list[str]',
        'zero_length_separator': 'str'
    }

    attribute_map = {
        'lang': 'lang',
        'texts': 'texts',
        'reference_texts': 'referenceTexts',
        'zero_length_separator': 'zeroLengthSeparator'
    }

    def __init__(self, lang=None, texts=None, reference_texts=None, zero_length_separator=None):  # noqa: E501
        """SpellCheckRequestDto - a model defined in Swagger"""  # noqa: E501

        self._lang = None
        self._texts = None
        self._reference_texts = None
        self._zero_length_separator = None
        self.discriminator = None

        if lang is not None:
            self.lang = lang
        if texts is not None:
            self.texts = texts
        if reference_texts is not None:
            self.reference_texts = reference_texts
        if zero_length_separator is not None:
            self.zero_length_separator = zero_length_separator

    @property
    def lang(self):
        """Gets the lang of this SpellCheckRequestDto.  # noqa: E501


        :return: The lang of this SpellCheckRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this SpellCheckRequestDto.


        :param lang: The lang of this SpellCheckRequestDto.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def texts(self):
        """Gets the texts of this SpellCheckRequestDto.  # noqa: E501


        :return: The texts of this SpellCheckRequestDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._texts

    @texts.setter
    def texts(self, texts):
        """Sets the texts of this SpellCheckRequestDto.


        :param texts: The texts of this SpellCheckRequestDto.  # noqa: E501
        :type: list[str]
        """

        self._texts = texts

    @property
    def reference_texts(self):
        """Gets the reference_texts of this SpellCheckRequestDto.  # noqa: E501


        :return: The reference_texts of this SpellCheckRequestDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._reference_texts

    @reference_texts.setter
    def reference_texts(self, reference_texts):
        """Sets the reference_texts of this SpellCheckRequestDto.


        :param reference_texts: The reference_texts of this SpellCheckRequestDto.  # noqa: E501
        :type: list[str]
        """

        self._reference_texts = reference_texts

    @property
    def zero_length_separator(self):
        """Gets the zero_length_separator of this SpellCheckRequestDto.  # noqa: E501


        :return: The zero_length_separator of this SpellCheckRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._zero_length_separator

    @zero_length_separator.setter
    def zero_length_separator(self, zero_length_separator):
        """Sets the zero_length_separator of this SpellCheckRequestDto.


        :param zero_length_separator: The zero_length_separator of this SpellCheckRequestDto.  # noqa: E501
        :type: str
        """

        self._zero_length_separator = zero_length_separator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpellCheckRequestDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpellCheckRequestDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
