# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from memsource_cli.models.machine_translate_settings_reference import MachineTranslateSettingsReference  # noqa: F401,E501
from memsource_cli.models.project_term_base_reference import ProjectTermBaseReference  # noqa: F401,E501
from memsource_cli.models.project_translation_memory_reference import ProjectTranslationMemoryReference  # noqa: F401,E501


class TranslationResourcesDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'machine_translate_settings': 'MachineTranslateSettingsReference',
        'translation_memories': 'list[ProjectTranslationMemoryReference]',
        'term_bases': 'list[ProjectTermBaseReference]'
    }

    attribute_map = {
        'machine_translate_settings': 'machineTranslateSettings',
        'translation_memories': 'translationMemories',
        'term_bases': 'termBases'
    }

    def __init__(self, machine_translate_settings=None, translation_memories=None, term_bases=None):  # noqa: E501
        """TranslationResourcesDto - a model defined in Swagger"""  # noqa: E501

        self._machine_translate_settings = None
        self._translation_memories = None
        self._term_bases = None
        self.discriminator = None

        if machine_translate_settings is not None:
            self.machine_translate_settings = machine_translate_settings
        if translation_memories is not None:
            self.translation_memories = translation_memories
        if term_bases is not None:
            self.term_bases = term_bases

    @property
    def machine_translate_settings(self):
        """Gets the machine_translate_settings of this TranslationResourcesDto.  # noqa: E501


        :return: The machine_translate_settings of this TranslationResourcesDto.  # noqa: E501
        :rtype: MachineTranslateSettingsReference
        """
        return self._machine_translate_settings

    @machine_translate_settings.setter
    def machine_translate_settings(self, machine_translate_settings):
        """Sets the machine_translate_settings of this TranslationResourcesDto.


        :param machine_translate_settings: The machine_translate_settings of this TranslationResourcesDto.  # noqa: E501
        :type: MachineTranslateSettingsReference
        """

        self._machine_translate_settings = machine_translate_settings

    @property
    def translation_memories(self):
        """Gets the translation_memories of this TranslationResourcesDto.  # noqa: E501


        :return: The translation_memories of this TranslationResourcesDto.  # noqa: E501
        :rtype: list[ProjectTranslationMemoryReference]
        """
        return self._translation_memories

    @translation_memories.setter
    def translation_memories(self, translation_memories):
        """Sets the translation_memories of this TranslationResourcesDto.


        :param translation_memories: The translation_memories of this TranslationResourcesDto.  # noqa: E501
        :type: list[ProjectTranslationMemoryReference]
        """

        self._translation_memories = translation_memories

    @property
    def term_bases(self):
        """Gets the term_bases of this TranslationResourcesDto.  # noqa: E501


        :return: The term_bases of this TranslationResourcesDto.  # noqa: E501
        :rtype: list[ProjectTermBaseReference]
        """
        return self._term_bases

    @term_bases.setter
    def term_bases(self, term_bases):
        """Sets the term_bases of this TranslationResourcesDto.


        :param term_bases: The term_bases of this TranslationResourcesDto.  # noqa: E501
        :type: list[ProjectTermBaseReference]
        """

        self._term_bases = term_bases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranslationResourcesDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslationResourcesDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
