# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TranslationRequestExtendedDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_texts': 'list[str]',
        '_from': 'str',
        'to': 'str',
        'filename': 'str'
    }

    attribute_map = {
        'source_texts': 'sourceTexts',
        '_from': 'from',
        'to': 'to',
        'filename': 'filename'
    }

    def __init__(self, source_texts=None, _from=None, to=None, filename=None):  # noqa: E501
        """TranslationRequestExtendedDto - a model defined in Swagger"""  # noqa: E501

        self._source_texts = None
        self.__from = None
        self._to = None
        self._filename = None
        self.discriminator = None

        self.source_texts = source_texts
        self._from = _from
        self.to = to
        if filename is not None:
            self.filename = filename

    @property
    def source_texts(self):
        """Gets the source_texts of this TranslationRequestExtendedDto.  # noqa: E501


        :return: The source_texts of this TranslationRequestExtendedDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._source_texts

    @source_texts.setter
    def source_texts(self, source_texts):
        """Sets the source_texts of this TranslationRequestExtendedDto.


        :param source_texts: The source_texts of this TranslationRequestExtendedDto.  # noqa: E501
        :type: list[str]
        """
        if source_texts is None:
            raise ValueError("Invalid value for `source_texts`, must not be `None`")  # noqa: E501

        self._source_texts = source_texts

    @property
    def _from(self):
        """Gets the _from of this TranslationRequestExtendedDto.  # noqa: E501


        :return: The _from of this TranslationRequestExtendedDto.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this TranslationRequestExtendedDto.


        :param _from: The _from of this TranslationRequestExtendedDto.  # noqa: E501
        :type: str
        """
        if _from is None:
            raise ValueError("Invalid value for `_from`, must not be `None`")  # noqa: E501

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this TranslationRequestExtendedDto.  # noqa: E501


        :return: The to of this TranslationRequestExtendedDto.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this TranslationRequestExtendedDto.


        :param to: The to of this TranslationRequestExtendedDto.  # noqa: E501
        :type: str
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    @property
    def filename(self):
        """Gets the filename of this TranslationRequestExtendedDto.  # noqa: E501


        :return: The filename of this TranslationRequestExtendedDto.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this TranslationRequestExtendedDto.


        :param filename: The filename of this TranslationRequestExtendedDto.  # noqa: E501
        :type: str
        """

        self._filename = filename

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranslationRequestExtendedDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslationRequestExtendedDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
