# coding: utf-8

"""
    Memsource REST API

    Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from memsource_cli.models.segment_reference import SegmentReference  # noqa: F401,E501


class UpdateIgnoredChecksDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'segment': 'SegmentReference',
        'warning_types': 'list[str]'
    }

    attribute_map = {
        'segment': 'segment',
        'warning_types': 'warningTypes'
    }

    def __init__(self, segment=None, warning_types=None):  # noqa: E501
        """UpdateIgnoredChecksDto - a model defined in Swagger"""  # noqa: E501

        self._segment = None
        self._warning_types = None
        self.discriminator = None

        self.segment = segment
        self.warning_types = warning_types

    @property
    def segment(self):
        """Gets the segment of this UpdateIgnoredChecksDto.  # noqa: E501


        :return: The segment of this UpdateIgnoredChecksDto.  # noqa: E501
        :rtype: SegmentReference
        """
        return self._segment

    @segment.setter
    def segment(self, segment):
        """Sets the segment of this UpdateIgnoredChecksDto.


        :param segment: The segment of this UpdateIgnoredChecksDto.  # noqa: E501
        :type: SegmentReference
        """
        if segment is None:
            raise ValueError("Invalid value for `segment`, must not be `None`")  # noqa: E501

        self._segment = segment

    @property
    def warning_types(self):
        """Gets the warning_types of this UpdateIgnoredChecksDto.  # noqa: E501


        :return: The warning_types of this UpdateIgnoredChecksDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._warning_types

    @warning_types.setter
    def warning_types(self, warning_types):
        """Sets the warning_types of this UpdateIgnoredChecksDto.


        :param warning_types: The warning_types of this UpdateIgnoredChecksDto.  # noqa: E501
        :type: list[str]
        """
        if warning_types is None:
            raise ValueError("Invalid value for `warning_types`, must not be `None`")  # noqa: E501
        allowed_values = ["EmptyTranslation", "TrailingPunctuation", "Formatting", "JoinTags", "MissingNumbers", "MultipleSpaces", "NonConformingTerm", "NotConfirmed", "TranslationLength", "TrailingSpace", "UnresolvedComment", "EmptyPairTags", "InconsistentTranslationTargetSource", "InconsistentTranslationSourceTarget", "ForbiddenString", "SpellCheck", "RepeatedWords", "InconsistentTagContent", "EmptyTagContent", "Malformed", "ForbiddenTerm", "NewerAtLowerLevel", "LeadingAndTrailingSpaces", "TargetSourceIdentical", "SourceOrTargetRegexp", "UnmodifiedFuzzyTranslation", "Moravia", "ExtraNumbers", "UnresolvedConversation", "NestedTags"]  # noqa: E501
        if not set(warning_types).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `warning_types` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(warning_types) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._warning_types = warning_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateIgnoredChecksDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateIgnoredChecksDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
